import os
from pathlib import Path

from config import (
    AUTO_GENERATE_INFER_CONFIG,
    INFER_CONFIG_PATH,
    LABELS_PATH,
    MUX_BATCH_SIZE,
    YOLO_CLUSTER_MODE,
    YOLO_CONFIDENCE_THRESHOLD,
    YOLO_CUSTOM_LIB_PATH,
    YOLO_ENGINE_PATH,
    YOLO_INPUT_DIMS,
    YOLO_INTERVAL,
    YOLO_NETWORK_MODE,
    YOLO_NMS_IOU_THRESHOLD,
    YOLO_NUM_CLASSES,
    YOLO_ONNX_PATH,
    YOLO_OUTPUT_BLOB_NAMES,
    YOLO_PARSE_BBOX_FUNC,
)
PROJECT_ROOT = Path(__file__).resolve().parents[1]


def abs_project_path(path: str) -> str:
    p = Path(path)
    if p.is_absolute():
        return str(p)
    return str(PROJECT_ROOT / p)

def _precision_name(network_mode: int) -> str:
    return {
        0: "fp32",
        1: "int8",
        2: "fp16",
    }.get(network_mode, "fp16")


def _default_engine_path() -> str:
    onnx_path = Path(YOLO_ONNX_PATH)
    precision = _precision_name(YOLO_NETWORK_MODE)
    return str(onnx_path.with_name(f"{onnx_path.name}_b{MUX_BATCH_SIZE}_gpu0_{precision}.engine"))


def ensure_primary_infer_config() -> str:
    if not AUTO_GENERATE_INFER_CONFIG:
        return INFER_CONFIG_PATH

    config_path = Path(INFER_CONFIG_PATH)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    engine_path = YOLO_ENGINE_PATH.strip() or _default_engine_path()
    lines = [
        "# Auto-generated by pipelines/model_config.py",
        "# Change YOLO_* values in config.py, then restart the server.",
        "",
        "[property]",
        "gpu-id=0",
        #f"onnx-file={YOLO_ONNX_PATH}",
        #f"model-engine-file={engine_path}",
        #f"labelfile-path={LABELS_PATH}",
        f"onnx-file={abs_project_path(YOLO_ONNX_PATH)}",
        f"model-engine-file={abs_project_path(engine_path)}",
        f"labelfile-path={abs_project_path(LABELS_PATH)}",
        "net-scale-factor=0.00392156862745098",
        "model-color-format=0",
        f"infer-dims={YOLO_INPUT_DIMS}",
        f"network-mode={YOLO_NETWORK_MODE}",
        f"batch-size={MUX_BATCH_SIZE}",
        f"interval={YOLO_INTERVAL}",
        "gie-unique-id=1",
        "process-mode=1",
        "network-type=0",
        f"num-detected-classes={YOLO_NUM_CLASSES}",
        f"cluster-mode={YOLO_CLUSTER_MODE}",
    ]

    if YOLO_CUSTOM_LIB_PATH.strip():
        lines.append(f"custom-lib-path={abs_project_path(YOLO_CUSTOM_LIB_PATH)}")
    if YOLO_PARSE_BBOX_FUNC.strip():
        lines.append(f"parse-bbox-func-name={YOLO_PARSE_BBOX_FUNC}")
    if YOLO_OUTPUT_BLOB_NAMES.strip():
        lines.append(f"output-blob-names={YOLO_OUTPUT_BLOB_NAMES}")

    lines.extend([
        "",
        "[class-attrs-all]",
        "topk=300",
        f"nms-iou-threshold={YOLO_NMS_IOU_THRESHOLD}",
        f"pre-cluster-threshold={YOLO_CONFIDENCE_THRESHOLD}",
        "",
    ])

    config_path.write_text("\n".join(lines), encoding="utf-8")

    if not os.path.exists(YOLO_ONNX_PATH):
        print(f"[WARN] YOLO_ONNX_PATH does not exist yet: {YOLO_ONNX_PATH}")
    if YOLO_CUSTOM_LIB_PATH.strip() and not os.path.exists(YOLO_CUSTOM_LIB_PATH):
        print(f"[WARN] YOLO_CUSTOM_LIB_PATH does not exist yet: {YOLO_CUSTOM_LIB_PATH}")

    return str(config_path)
